### ISSUE TITLE
All the modules are brokey.....

### ISSUE THREAD

**Issue by ToxicAven** [jraffstar/gsplusplusleak-decomp#1]
lol this client is dead shit, nice try to get 5 seconds of fame, maybe don't deobf the fake version the dev leaked :trollface:

**Comment by jraffstar** [comment]
I made a joke that my shitty gs wasnt a shitty gs++ skid so he told me that the jar was deobf so i decompiled and put it here cuz I can. Im not looking for fame I just want an excuse to put another github repo up
